#mkdocs.yml
site_name: Documentación VsCode + MkDocs
theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: blue
  
extra:
  logo: images/logo.png
  favicon: images/logo.png

nav:
  - 0. Inicio: index.md
  - 1. Visual Studio Code: guia-vscode.md
  - 2. MkDocs: guia-mkdocs.md