#mkdocs.yml
site_name: Documentación VsCode + MkDocs
site_url: https://javidocenteinformatica.github.io/vscode_mkdocs/
repo_url: https://github.com/javiDocenteInformatica/vscode_mkdocs
theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: blue
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

## Sólo funciona si eres insider. Esto te permitiría abrir enlaces en una nueva pestaña.
# plugins:
#   - privacy:
#       links_attr_map:
#         target: _blank
#         rel: noopener noreferrer

nav:
  - 0. Inicio: index.md
  - 1. Visual Studio Code: guia-vscode.md
  - 2. MkDocs: guia-mkdocs.md