#mkdocs.yml
site_name: Documentación VsCode + MkDocs
site_url: https://javidocenteinformatica.github.io/vscode_mkdocs/
repo_url: https://github.com/javiDocenteInformatica/vscode_mkdocs
theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: blue
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    # - navigation.tabs
    - navigation.top
    # - navigation.instant
    - navigation.expand
    # - navigation.sections
    # - navigation.tracking
    # - navigation.tabs.sticky
    - navigation.footer

plugins: # https://github.com/mihaigalos/mkdocs-breadcrumbs-plugin
  - mkdocs-breadcrumbs-plugin:
      delimiter: " / "  # separator between sections
      log_level: "WARNING"  # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        # - "docs/mkdocs/**"
        - "docs/mkdocs/**"   # avoid generating index.md
        - "docs/vs_code/**"   # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
      use_page_titles: true # use page title instead of path in breadcrumbs
      home_text: "Inicio"

## Sólo funciona si eres insider. Esto te permitiría abrir enlaces en una nueva pestaña.
# plugins:
#   - privacy:
#       links_attr_map:
#         target: _blank
#         rel: noopener noreferrer

nav:
  - Inicio: index.md
  - 1. Visual Studio Code:
      - Guía: vs_code/guia-vscode.md
  - 2. MkDocs:
      - Guía: mkdocs/guia-mkdocs.md